### ISSUE TITLE
前端需要驗證登入狀態的解決方案

### ISSUE THREAD

**Issue by DevilTea** [MikuEngineering/missue-tracker-backend#24]
Hi, 前端突然想到保持登入這件事情需要類似以下的 API，
加上前端路由也要在渲染業面前判斷是否重新導向，
再請後端夥伴一起討論是否實作或有其他替代方案！

### (Private) `GET` - `/api/session`
驗證登入狀態

#### Response
- 200 OK 登入
- 401 Unauthorized 未登入

**Comment by PinLin** [comment]
@DevilTea 如果成功呼叫這個 API 的話，會需要回傳怎麼樣的 body 呢？

另外想問，是否要將未登入的 401 Unauthorized 改為 404 Not Found？

謝謝！

![圖片](https://user-images.githubusercontent.com/10110499/70762816-fe761580-1d8c-11ea-9020-8351b45ff91b.png)

**Comment by DevilTea** [comment]
@PinLin 成功的 response body 不需要有甚麼內容，

此 API 其實只是做為向後端進行 cookies 內 session token 是否有效的驗證，

選擇 401 的原因是，401本身就有著未登入、伺服器無法辨識是誰的意涵，

所以我認為 401 比起 404 來說更為合適！

**Comment by PinLin** [comment]
@DevilTea 我認為狀態碼 401 代表客戶端因為驗證上的問題而無法使用此 API 來完成其呼叫的目的
然而此 API 的目的應是驗證客戶端與伺服器之間的會話關係是否存在
如果回傳 401，意思便為「沒有權限驗證客戶端與伺服器之間的會話關係是否存在」
而回傳 404 的話則是比較接近我們原意的「客戶端與伺服器之間的會話關係不存在」
因此我認為將此 API 設為 Public 並於會話關係不存在時回傳 404，應是一個較好的選擇！

**Comment by PinLin** [comment]
@DevilTea 因為時間關係，這邊後端會先實作您原本的需求，待共識凝聚後視情況再來做修改的動作

**Comment by DevilTea** [comment]
@PinLin 就 404 吧！

**Comment by DevilTea** [comment]
@PinLin 順便幫我更新在 api 文件上，我會直接依照 api 文件記載的規格來使用

**Comment by PinLin** [comment]
@DevilTea 了解！

**Comment by PinLin** [comment]
@DevilTea 我妥協了！真香！
<img width="357" alt="" src="https://user-images.githubusercontent.com/10110499/70859116-3f1a8e00-1f49-11ea-9fb0-9ddb3f7966ff.png">

**Comment by PinLin** [comment]
@DevilTea 光明會

![external-content duckduckgo com](https://user-images.githubusercontent.com/10110499/70860010-ed790000-1f56-11ea-9ab9-2e67c536000f.jpeg)

### (Public) GET - `/api/session`
驗證登入狀態

#### Response
- 200 OK
已經登入
- 404 Not Found
尚未登入
