### ISSUE TITLE
編輯使用者資料的 API 規格改變

### ISSUE THREAD

**Issue by PinLin** [MikuEngineering/missue-tracker-backend#54]
### (Private) `PUT` - `/api/users/:id`
編輯使用者資料

| Task         | Progress|
| --------     | --------|
| Unauthorized | OK|
| Forbidden    | OK|
| Not Found    | OK|
| Success      | OK|

#### Request
```json
{
    "nickname": string,
    "email": string,
    "autobiography": string,
}

**Comment by virtualprism** [comment]
改好了
